# Site settings
title: MALI NERED
email: sankovic.marko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  No description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://markosankovic.github.io" # the base hostname & protocol for your site
twitter_username: markosankovic
github_username:  markosankovic
linkedin_username: markosankovic
instagram_username: ce_la_vii


# Build settings
markdown: kramdown
